modules/erp/urls.py
from django.urls import path

from . import views

app_name = 'erp'
urlpatterns = [
    path('', views.erp, name='index'),

    path('conta/excluir/', views.account_delete, name='account_delete'),

    path('membro/<int:pk>/excluir', views.member_delete, name='member_delete'),

    path(
        'alterar-senha/',
        views.PasswordChange.as_view(),
        name='password_change',
    ),
]

modules/users/urls.py
from django.urls import path
from django.conf import settings
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.signin, name='login'),
    path('cadastro/', views.register, name='register'),
    
    path(
        'sair/',
        LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL),
        name='logout'
    ),
]

server/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('modules.users.urls')),
    path('erp/', include('modules.erp.urls')),
    path('caixa/', include('modules.finance.urls')),
    path('contatos/', include('modules.contacts.urls')),

    # temporary: while the index page is not built
    path(
        '',
        TemplateView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path(
        'recuperar-senha/', 
        auth_views.PasswordResetView.as_view(),
        name='reset_password'
    ),
    path(
        'recuperar-senha/enviado/', 
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'recuperar-senha/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'recuperar-senha/fim/', 
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),
]

modules/erp/models.py
from django.db import models
from django.core.validators import MinLengthValidator


class Company(models.Model):
    razao_social = models.CharField(max_length=255, blank=True, null=True)
    fantasia = models.CharField(max_length=255, blank=True, null=True)
    cnpj = models.CharField(
        max_length=18, primary_key=True, 
        validators=[MinLengthValidator(14)]
    )
    ie = models.CharField(max_length=50, blank=True, null=True)
    endereco = models.CharField(max_length=255, blank=True, null=True)
    numero = models.PositiveIntegerField(blank=True, null=True)
    bairro = models.CharField(max_length=255, blank=True, null=True)
    complemento = models.CharField(max_length=255, blank=True, null=True)
    cidade = models.CharField(max_length=255, blank=True, null=True)
    uf = models.CharField(max_length=2, blank=True, null=True)    
    cep = models.CharField(max_length=9, blank=True, null=True)
    celular = models.CharField(max_length=14, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    logo = models.ImageField(
        blank=True, null=True,
        upload_to='media/logos',
    )

    def __str__(self):
        if self.cnpj:
            return f'{self.fantasia} [{self.cnpj}]'
        else:
            return f'cadastro incompleto'
        

erp/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.forms import ModelForm

from .models import Company

from users.models import User


class CompanyForm(ModelForm):
    class Meta:
        model = Company
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CompanyForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({
                'autofocus': True,
                'placeholder': '...',
                'class': '''
                    w-fit
                    text-ellipsis
                    text-xs
                    text-end
                    bg-transparent
                    text-black/40
                    dark:text-white/40
                    outline-none''',
            })    

        for field_name in ['cnpj', 'ie', 'numero', 'cep', 'celular']:
            if field_name in self.fields:
                self.fields[field_name].widget.attrs['inputmode'] = 'decimal'


class MemberCreationForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            'email',
            'name',
            'username',
        ]

    def __init__(self, *args, **kwargs):
        super(MemberCreationForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({
                'autofocus': True,
                'placeholder': '...',
                'class': '''
                    w-fit
                    text-xs
                    text-end
                    text-ellipsis
                    bg-transparent
                    text-black/40
                    dark:text-white/40
                    outline-none''',
            })    


    def save(self, commit=True):
        user = super().save(commit=False)
        if user.username:
            user.username = user.username.lower()
        if commit:
            user.save()
        return user                

modules/erp/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.forms import ModelForm

from .models import Company

from modules.users.models import User


class CompanyForm(ModelForm):
    class Meta:
        model = Company
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CompanyForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({
                'autofocus': True,
                'placeholder': '...',
                'class': '''
                    w-fit
                    text-ellipsis
                    text-xs
                    text-end
                    bg-transparent
                    text-black/40
                    dark:text-white/40
                    outline-none''',
            })    

        for field_name in ['cnpj', 'ie', 'numero', 'cep', 'celular']:
            if field_name in self.fields:
                self.fields[field_name].widget.attrs['inputmode'] = 'decimal'


class MemberCreationForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            'email',
            'name',
            'username',
        ]

    def __init__(self, *args, **kwargs):
        super(MemberCreationForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({
                'autofocus': True,
                'placeholder': '...',
                'class': '''
                    w-fit
                    text-xs
                    text-end
                    text-ellipsis
                    bg-transparent
                    text-black/40
                    dark:text-white/40
                    outline-none''',
            })    


    def save(self, commit=True):
        user = super().save(commit=False)
        if user.username:
            user.username = user.username.lower()
        if commit:
            user.save()
        return user                

erp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from users.models import User

from .services import Settings    


@login_required(login_url='users:login')
def erp(request):
    context = Settings.context(request)

    return render(request, 'erp/index.html', context)


@login_required(login_url='users:login')
def account_delete(request):
    user = request.user
    company = user.company

    if request.method == 'POST':
        if company:
            company.delete()
        else:
            user.delete()
            
    return redirect('users:register')


@login_required(login_url='users:login')
def member_delete(request, pk):
    user = User.objects.get(pk=pk)

    if request.method == 'POST' and 'member-delete' in request.POST:
        user.delete()

    return redirect('erp:index')   
    

class PasswordChange(LoginRequiredMixin, PasswordChangeView):
    template_name = 'erp/common/_password.html'
    success_url = reverse_lazy('erp:index')   
    login_url = 'users:login' 

modules/erp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from modules.users.models import User

from .services import Settings    


@login_required(login_url='users:login')
def erp(request):
    context = Settings.context(request)

    return render(request, 'erp/index.html', context)


@login_required(login_url='users:login')
def account_delete(request):
    user = request.user
    company = user.company

    if request.method == 'POST':
        if company:
            company.delete()
        else:
            user.delete()
            
    return redirect('users:register')


@login_required(login_url='users:login')
def member_delete(request, pk):
    user = User.objects.get(pk=pk)

    if request.method == 'POST' and 'member-delete' in request.POST:
        user.delete()

    return redirect('erp:index')   
    

class PasswordChange(LoginRequiredMixin, PasswordChangeView):
    template_name = 'erp/common/_password.html'
    success_url = reverse_lazy('erp:index')   
    login_url = 'users:login' 

modules/erp/templates/erp/desktop/_navbar.html
{% load erp %}

<div
    class="
        rounded-lg
        justify-between 
        dark:shadow-thick 
        items-end 
        lg:flex
        flex-col
        hidden
        p-4
        h-full
        bg-background
        dark:bg-primary
        relative">

    <!--user info-->
    <div class="w-full">
        <p 
            class="
            text-xl font-normal lg:text-8xl tracking-tight 
            text-primary dark:text-white"> 

            <div class="relative flex items-center gap-x-4">
                <div class="flex gap-x-1 justify-center">
                    <button
                        class="
                        w-9 h-9
                        rounded-md
                        text-zinc-700
                        bg-black/5
                        dark:text-zinc-100
                        dark:bg-tertiary">
                        {{ request.user.name | first}}
                    </button>
                </div>
                <div class="text-sm leading-5">
                    <p class="font-semibold text-primary dark:text-white">
                    <a href="{% url "erp:index" %}">
                        <span class="absolute inset-0"></span>
                        {{ request.user.name | first_name }}
                    </a>
                    </p>
                    <p class="text-zinc-500 dark:text-zinc-400">
                        {{ request.user.email }}
                    </p>
                </div>
            </div>
        </p>
    </div>   
    
    <!--user edit button-->
    <div class="absolute top-0 right-0 p-4 text-xl leading-5">
            <div class="relative inline-block group">
                <button 
                    id="settingsButton" 
                    class="text-black dark:text-white outline-none">
                    ...
                </button>

                {% comment %}
                <!--dropdown-->
                <div class="absolute -top-1">
                    <div
                        class="
                            relative
                            ml-5
                            left-0
                            hidden
                            group-hover:block
                            aspect-square
                            ring-1 
                            ring-primary/5 hover:ring-primary/5
                            dark:ring-white/10 dark:hover:ring-white/20
                            duration-300
                            transition-all
                            group
                            end-0 z-10 w-[125px]
                            divide-y divide-black/10 dark:divide-white/15
                            rounded-lg
                            border border-black/10 
                            bg-white/25 dark:bg-secondary/60
                            backdrop-blur-md     
                            shadow-md"
                        role="menu">

                        <div class="p-1">
                        <a
                            href="{% url "erp:index" %}"
                            class="
                            block
                            rounded-md
                            px-4 py-1
                            text-[13px]
                            text-zinc-500 dark:text-zinc-400
                            hover:bg-black/5 hover:text-zinc-600 
                            dark:hover:bg-tertiary dark:hover:text-zinc-200"
                            role="menuitem">
                            😗
                        </a>

                        <a
                            href="{% url "erp:password_change" %}"
                            class="
                            block
                            rounded-md
                            px-4 py-1
                            text-[13px]
                            text-zinc-500 dark:text-zinc-400
                            hover:bg-black/5 hover:text-zinc-600 
                            dark:hover:bg-tertiary dark:hover:text-zinc-200"
                            role="menuitem">
                            alterar senha
                        </a>                        


                        <button
                            type="submit"
                            id="settingsButton"
                            class="
                                flex
                                w-full
                                items-center
                                gap-2
                                rounded-md
                                px-4 py-1
                                text-[13px] 
                                text-zinc-500 dark:text-zinc-400
                                hover:bg-black/5 hover:text-zinc-600 
                                dark:hover:bg-tertiary dark:hover:text-zinc-200"
                            role="menuitem">          
                            ajustes
                        </button>
                        </div>

                        <div class="p-1">
                            <form 
                                action="{% url "users:logout" %}"
                                method="POST">
                                {% csrf_token %}
                                <button
                                    type="submit"
                                    class="
                                        flex
                                        w-full
                                        items-center
                                        gap-2
                                        rounded-md
                                        px-4 py-1
                                        text-[13px] 
                                        text-zinc-500 dark:text-zinc-400
                                        hover:bg-black/5 hover:text-zinc-600 
                                        dark:hover:bg-tertiary dark:hover:text-zinc-200"
                                    role="menuitem">          
                                    sair
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
                {% endcomment %}                   
            </div>
    </div>

    <!--atalho a-->
    <div class="absolute bottom-0 left-0 p-4 leading-4">
            <span class="text-[12px] text-zinc-400">
                atalho para ajustes
            </span>
            <kbd 
                class="
                    px-[5px] py-[2px]
                    text-xs
                    text-zinc-500
                    border 
                    border-zinc-300 
                    rounded-md
                    dark:bg-tertiary
                    dark:text-white/60
                    dark:border-white/20">
                a
            </kbd>
    </div>

</div>