modules/contacts/urls.py
from django.urls import path

from . import views

app_name = 'contacts'
urlpatterns = [
    path('', views.contacts, name='main'),
    path('edit/<int:pk>/', views.edit_contact, name='edit_contact'),
    path('excluir/<int:pk>/', views.delete_contact, name='delete_contact'),
]

modules/erp/urls.py
from django.urls import path

from . import views

app_name = 'erp'
urlpatterns = [
    path('', views.erp, name='index'),

    path('conta/excluir/', views.account_delete, name='account_delete'),

    path('membro/<int:pk>/excluir', views.member_delete, name='member_delete'),

    path(
        'alterar-senha/',
        views.PasswordChange.as_view(),
        name='password_change',
    ),
]

server/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('modules.users.urls')),
    path('erp/', include('modules.erp.urls')),
    path('caixa/', include('modules.finance.urls')),
    path('contatos/', include('modules.contacts.urls')),

    # temporary: while the index page is not built
    path(
        '',
        TemplateView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path(
        'recuperar-senha/', 
        auth_views.PasswordResetView.as_view(),
        name='reset_password'
    ),
    path(
        'recuperar-senha/enviado/', 
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'recuperar-senha/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'recuperar-senha/fim/', 
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),
]

contacts/models.py
from django.db import models

from erp.models import Company


class Contacts(models.Model):
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name='contacts')
    created = models.DateTimeField(auto_now_add=True)

    nome = models.CharField(max_length=255)
    apelido = models.CharField(max_length=255, blank=True)    
    pessoa = models.CharField(max_length=255)
    cpf_cnpj = models.CharField(max_length=18, unique=True)
    contribuinte = models.CharField(max_length=255, blank=True)
    ie = models.IntegerField(blank=True, null=True)
    im = models.IntegerField(blank=True, null=True)
    tipo = models.CharField(max_length=255, blank=True)
    status = models.CharField(max_length=255, blank=True, default='ativo')

    celular = models.CharField(max_length=15, blank=True)
    email = models.EmailField(blank=True)

    endereco = models.CharField(max_length=255, blank=True)
    numero = models.PositiveIntegerField(blank=True, null=True)
    bairro = models.CharField(max_length=255, blank=True)
    complemento = models.CharField(max_length=30, blank=True)
    cidade = models.CharField(max_length=255, blank=True)
    uf = models.CharField(max_length=2, blank=True)    
    cep = models.CharField(max_length=9, blank=True)

    nascimento = models.DateField(blank=True, null=True)
    observacoes = models.CharField(max_length=255, blank=True)
    anexos = models.FileField(upload_to='media/anexos', blank=True, null=True)

    def __str__(self):
        return self.nome
    
    class Meta:
        ordering = ['nome']

modules/contacts/models.py
from django.db import models

from modules.erp.models import Company


class Contacts(models.Model):
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name='contacts')
    created = models.DateTimeField(auto_now_add=True)

    nome = models.CharField(max_length=255)
    apelido = models.CharField(max_length=255, blank=True)    
    pessoa = models.CharField(max_length=255)
    cpf_cnpj = models.CharField(max_length=18, unique=True)
    contribuinte = models.CharField(max_length=255, blank=True)
    ie = models.IntegerField(blank=True, null=True)
    im = models.IntegerField(blank=True, null=True)
    tipo = models.CharField(max_length=255, blank=True)
    status = models.CharField(max_length=255, blank=True, default='ativo')

    celular = models.CharField(max_length=15, blank=True)
    email = models.EmailField(blank=True)

    endereco = models.CharField(max_length=255, blank=True)
    numero = models.PositiveIntegerField(blank=True, null=True)
    bairro = models.CharField(max_length=255, blank=True)
    complemento = models.CharField(max_length=30, blank=True)
    cidade = models.CharField(max_length=255, blank=True)
    uf = models.CharField(max_length=2, blank=True)    
    cep = models.CharField(max_length=9, blank=True)

    nascimento = models.DateField(blank=True, null=True)
    observacoes = models.CharField(max_length=255, blank=True)
    anexos = models.FileField(upload_to='media/anexos', blank=True, null=True)

    def __str__(self):
        return self.nome
    
    class Meta:
        ordering = ['nome']

modules/contacts/forms.py
from django.forms import ModelForm

from .models import Contacts


class ContactsForm(ModelForm):
    class Meta:
        model = Contacts
        fields = '__all__'

modules/contacts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .services import ContactsLogic

from .models import Contacts


@login_required(login_url='users:login')
def contacts(request):
    context = {}
    context.update(ContactsLogic.get_context(request))

    return render(request, 'contacts/main.html', context)

@login_required(login_url='users:login')
def edit_contact(request, pk):
    context = ContactsLogic.edit_contact(request, pk)

    return render(request, 'contacts/common/_edit_contact.html', context)

@login_required(login_url='users:login')
def delete_contact(request, pk):
    contact = Contacts.objects.get(pk=pk)
    contact.delete()
    
    return redirect('contacts:main')

modules/contacts/templates/contacts/common/_contacts.html
{% load static %}
{% load contacts %}

<div class="
    sm:px-3
    col-span-2
    relative">

    <p class="text-4xl font-medium text-black dark:text-white mt-6 sm:mt-14 px-1">
        <kbd>contatos</kbd>
    </p>    

    <div class="flex flex-wrap items-center w-full gap-2 md:flex-nowrap sm:gap-5 mb-5 mt-1">
        <!--searchbar-->
        <form action="{% url "contacts:main" %}" method="GET" class="relative w-full sm:w-1/2 h-8 sm:h-7 mb-2 sm:mb-0 px-1 rounded-lg">
            <svg
                class="absolute top-1/2 left-3 -translate-y-1/2 w-4 h-4 text-black/50 dark:text-white/50" 
                xmlns="http://www.w3.org/2000/svg" 
                fill="none" 
                viewBox="0 0 24 24" 
                stroke-width="1.5" 
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
            </svg>        
            <input
                class="
                w-full h-full pl-7 items-center p-2
                text-sm text-black/50 dark:text-white/50 
                rounded-lg 
                bg-[rgba(0,0,0,0.02)] dark:bg-tertiary
                ring-1 ring-black/10 dark:ring-white/15
                outline-none
                placeholder:text-black/30 dark:placeholder:text-white/30"
                placeholder="pesquisar por nome, apelido, celular ou cpf"
                type="text"
                name="q"
                autofocus>
        </form>

        <!--filter buttons-->    
        <div class="
            overflow-hidden
            w-full
            items-center justify-between
            relative">

            <div class="
                justify-start
                relative
                overflow-auto
                flex">
                
                <div class="overflow-x-auto px-1 py-1 pb-1 flex gap-3 no-scrollbar">
                <a id="semana" href="?filtro=todos{% if request.GET.banco %}&banco={{ request.GET.banco }}{% endif %}"
                    class="
                    tracking-wide
                    px-3 py-[3px] sm:px-3 sm:py-[4px]
                    ring-1
                    text-[13px]
                    {% if request.GET.filtro == 'todos' %}
                        bg-blue-50 dark:bg-blue-950
                        text-blue-500 dark:text-blue-200
                        ring-blue-500 dark:ring-blue-500
                    {% else %}
                        text-black/40 dark:text-white/55
                        ring-black/10 dark:ring-white/20
                        dark:bg-primary
                    {% endif %}
                    relative  
                    rounded-full flex-shrink-0">     
                    <span class="">todos</span>
                </a>  

                <a id="todos" href="?filtro=cliente{% if request.GET.banco %}&banco={{ request.GET.banco }}{% endif %}"
                    class="
                    tracking-wide
                    px-3 py-[3px] sm:px-3 sm:py-[4px]
                    ring-1
                    text-[13px]
                    {% if request.GET.filtro == 'cliente' %}
                        bg-blue-50 dark:bg-blue-950
                        text-blue-500 dark:text-blue-200
                        ring-blue-500 dark:ring-blue-500
                    {% else %}
                        text-black/40 dark:text-background/55
                        ring-black/10 dark:ring-white/20
                        dark:bg-primary
                    {% endif %}
                    relative  
                    rounded-full flex-shrink-0">  
                    <span class="">clientes</span>
                </a> 

                <a id="hoje" href="?filtro=fornecedor{% if request.GET.banco %}&banco={{ request.GET.banco }}{% endif %}"
                    class="
                    tracking-wide
                    px-3 py-[3px] sm:px-3 sm:py-[4px]
                    ring-1
                    text-[13px]
                    {% if request.GET.filtro == 'fornecedor' %}
                        bg-blue-50 dark:bg-blue-950
                        text-blue-500 dark:text-blue-200
                        ring-blue-500 dark:ring-blue-500
                    {% else %}
                        text-black/40 dark:text-white/55
                        ring-black/10 dark:ring-white/20
                        dark:bg-primary
                    {% endif %}
                    relative  
                    rounded-full flex-shrink-0">    
                    <span>fornecedores</span>
                </a> 

                <a id="semana" href="?filtro=vendedor{% if request.GET.banco %}&banco={{ request.GET.banco }}{% endif %}"
                    class="
                    tracking-wide
                    px-3 py-[3px] sm:px-3 sm:py-[4px]
                    ring-1
                    text-[13px]
                    {% if request.GET.filtro == 'vendedor' %}
                        bg-blue-50 dark:bg-blue-950
                        text-blue-500 dark:text-blue-200
                        ring-blue-500 dark:ring-blue-500
                    {% else %}
                        text-black/40 dark:text-white/55
                        ring-black/10 dark:ring-white/20
                        dark:bg-primary
                    {% endif %}
                    relative  
                    rounded-full flex-shrink-0">     
                    <span class="">vendedores</span>
                </a>                          
                </div>    
            </div>
        </div>   
    </div>

    {% if not request.GET.q and request.GET.filtro != 'cliente' and request.GET.filtro != 'fornecedor' and request.GET.filtro != 'vendedor' %}
    <p class="text-lg text-black/30 dark:text-white/50 mt-2 px-3">
        recentes
    </p>   
    <!--contacts-->
    <div class="
        mt-1 px-1
        grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4
        gap-3">

        {% for contact in recent_contacts %}
        <div
            class="
            p-2
            outline-none
            ring-1
            ring-black/5 dark:ring-white/10 dark:hover:ring-white/20
            shadow-sm hover:shadow-lg 
            relative
            rounded-xl
            bg-white/50
            dark:bg-secondary/50 
            min-h-[150px]
            w-full
            flex-shrink-0">

            <div class="flex items-center justify-between h-[30px] w-full rounded-xl mb-[5px]">
                <button class="bg-black/5 dark:bg-tertiary w-fit px-4 py-1 rounded-full">
                    <p
                        class="
                        text-nowrap text-xs font-medium tracking-wide
                        text-black/40 dark:text-white/60
                        truncate">
                        {% if contact.celular %}
                        {{ contact.celular | format_phone_number }}
                        {% else %}
                        cadastrar celular
                        {% endif %}
                    </p>
                </button>  
                <div class="w-fit h-fit">
                    <p
                        class="
                        text-nowrap text-xs font-medium
                        text-black/40 dark:text-white/60
                        truncate">
                        <kbd>{{ contact.id }}</kbd>
                    </p>
                </div>                             
            </div>        

            <a  href="{% url "contacts:edit_contact" contact.id %}"
                class="flex flex-col justify-between items-start bg-black/5 dark:bg-tertiary w-full h-[130px] rounded-xl">  
                <div class="px-3 py-2">
                    <div
                        class="
                        text-start text-sm mb-9
                        text-black/30 dark:text-white/30
                        truncate">
                        <svg class="size-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                            <path fill-rule="evenodd" d="M4.5 7.5a3 3 0 0 1 3-3h9a3 3 0 0 1 3 3v9a3 3 0 0 1-3 3h-9a3 3 0 0 1-3-3v-9Z" clip-rule="evenodd" />
                        </svg>                                               
                    </div> 

                    <p
                        class="
                        w-full relative
                        text-start text-lg font-medium
                        text-black/55 dark:text-white
                        truncate">
                        {{ contact.apelido }}                                
                    </p>      

                    
                    <div
                        class="
                        w-full bottom-1 relative
                        text-xs text-start
                        text-black/40 dark:text-white/40
                        truncate">
                        
                        <span class="">
                            {{ contact.nome }}
                        </span>          
                        <span class="line-clamp-1">
                            {{ contact.cpf_cnpj | format_cpf_cnpj }}
                        </span>                                                   
                    </div>                       
                </div>                    
            </a>
        </div>  
        {% endfor %}
      
    </div> 
    {% endif %}

    <p class="text-lg text-black/30 dark:text-white/50 mt-6 px-3">
        {% if request.GET.q %} resultados para: "{{ request.GET.q }}"
        {% elif request.GET.filtro == 'cliente' %}
        clientes
        {% elif request.GET.filtro == 'fornecedor' %}
        fornecedores
        {% elif request.GET.filtro == 'vendedor' %}
        vendedores
        {% else %}
        todos 
        {% endif %}
    </p>
    <!--contacts-->
    <div class="
        mt-1 px-1
        grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4
        gap-3">

        {% for contact in contacts %}
        <div
            class="
            p-2
            outline-none
            ring-1
            ring-black/5 dark:ring-white/10 dark:hover:ring-white/20
            shadow-sm hover:shadow-lg 
            relative
            rounded-xl
            bg-white/50
            dark:bg-secondary/50 
            min-h-[150px]
            w-full
            flex-shrink-0">

            <div class="flex items-center justify-between h-[30px] w-full rounded-xl mb-[5px]">
                <button class="bg-black/5 dark:bg-tertiary w-fit px-4 py-1 rounded-full">
                    <p
                        class="
                        text-nowrap text-xs font-medium tracking-wide
                        text-black/40 dark:text-white/60
                        truncate">
                        {% if contact.celular %}
                        {{ contact.celular | format_phone_number }}
                        {% else %}
                        cadastrar celular
                        {% endif %}
                    </p>
                </button>  
                <div class="w-fit h-fit">
                    <p
                        class="
                        text-nowrap text-xs font-medium
                        text-black/40 dark:text-white/60
                        truncate">
                        <kbd>{{ contact.id }}</kbd>
                    </p>
                </div>                             
            </div>        

            <a  href="{% url "contacts:edit_contact" contact.id %}"
                class="contact-info-button flex flex-col justify-between items-start bg-black/5 dark:bg-tertiary w-full h-[130px] rounded-xl">  
                <div class="px-3 py-2">
                    <div
                        class="
                        text-start text-sm mb-9
                        text-black/30 dark:text-white/30
                        truncate">
                        <svg class="size-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                            <path fill-rule="evenodd" d="M4.5 7.5a3 3 0 0 1 3-3h9a3 3 0 0 1 3 3v9a3 3 0 0 1-3 3h-9a3 3 0 0 1-3-3v-9Z" clip-rule="evenodd" />
                        </svg>                                               
                    </div> 

                    <p
                        class="
                        w-full relative
                        text-start text-lg font-medium
                        text-black/55 dark:text-white
                        truncate">
                        {{ contact.apelido }}                                
                    </p>      

                    
                    <div
                        class="
                        w-full bottom-1 relative
                        text-xs text-start
                        text-black/40 dark:text-white/40
                        truncate">
                        
                        <span class="">
                            {{ contact.nome }}
                        </span>          
                        <span class="line-clamp-1">
                            {{ contact.cpf_cnpj | format_cpf_cnpj }}
                        </span>                                                   
                    </div>                       
                </div>                    
            </a>
        </form>
        </div>  
        {% endfor %}
      
    </div> 
       
</div>

modules/contacts/templates/contacts/common/_header.html
<div
    class="
        relative
        col-span-2
        rounded-lg
        mt-2">      

    <!--back button-->
    <div class="absolute top-1 left-0 sm:left-3 flex items-center z-10">
        <div class="flex justify-center">
            <a 
                href="{% url "erp:index" %}"
                class="w-9 h-9">
                <svg class="w-6 h-6 text-zinc-400 dark:text-white/60" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m15 19-7-7 7-7"/>
                </svg> 
            </a>
        </div>
    </div>

    <!--add contato button-->
    <div
        class="
            absolute
            items-center
            grid
            grid-cols-1 gap-0
            right-0 sm:right-3 top-0
            w-fit">

        <button
            id="addContactButton"
            class="
            z-10
            relative  
            rounded-full
            outline-none">        
            <svg class="size-[30px] fill-black dark:fill-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path fill-rule="evenodd" d="M17.834 6.166a8.25 8.25 0 1 0 0 11.668.75.75 0 0 1 1.06 1.06c-3.807 3.808-9.98 3.808-13.788 0-3.808-3.807-3.808-9.98 0-13.788 3.807-3.808 9.98-3.808 13.788 0A9.722 9.722 0 0 1 21.75 12c0 .975-.296 1.887-.809 2.571-.514.685-1.28 1.179-2.191 1.179-.904 0-1.666-.487-2.18-1.164a5.25 5.25 0 1 1-.82-6.26V8.25a.75.75 0 0 1 1.5 0V12c0 .682.208 1.27.509 1.671.3.401.659.579.991.579.332 0 .69-.178.991-.579.3-.4.509-.99.509-1.671a8.222 8.222 0 0 0-2.416-5.834ZM15.75 12a3.75 3.75 0 1 0-7.5 0 3.75 3.75 0 0 0 7.5 0Z" clip-rule="evenodd" />
            </svg>              
        </button>    
    </div>  
    
</div>