modules/finance/urls.py
from django.urls import path

from . import views


app_name = 'finance'
urlpatterns = [
    path('', views.caixa, name='caixa'),
    path(
        'lancamento/<str:pk>/excluir/',
        views.delete_transaction,
        name='delete_transaction',
    ),
    path(
        'banco/<str:pk>/excluir/',
        views.delete_bank,
        name='delete_bank'
    ),
]

server/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('modules.users.urls')),
    path('erp/', include('modules.erp.urls')),
    path('caixa/', include('modules.finance.urls')),
    path('contatos/', include('modules.contacts.urls')),

    # temporary: while the index page is not built
    path(
        '',
        TemplateView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path(
        'recuperar-senha/', 
        auth_views.PasswordResetView.as_view(),
        name='reset_password'
    ),
    path(
        'recuperar-senha/enviado/', 
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'recuperar-senha/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'recuperar-senha/fim/', 
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),
]

finance/models.py
from django.db import models
from django.core.exceptions import ValidationError

from erp.models import Company
from users.models import User
from contacts.models import Contacts

import uuid


class BankAccount(models.Model):
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
        )        
    created = models.DateTimeField(auto_now_add=True)
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name='banks',
    )
    nome = models.CharField(max_length=255)
    agencia = models.CharField(max_length=255, blank=True)
    conta = models.CharField(max_length=255, blank=True)
    saldo = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True, default=0,
    )

    def __str__(self):
        return f'{self.nome}'
    

class Categories(models.Model):
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
        )
    parent = models.ForeignKey(
        'self', 
        on_delete=models.CASCADE, 
        related_name='subcategories',
        blank=True, 
        null=True, 
    )
    nome = models.CharField(max_length=150)
    is_active = models.BooleanField(default=True)
    is_group = models.BooleanField(default=False)

    def clean(self):
        if self.parent and not self.parent.is_group:
            raise ValidationError("Parent must have is_group=True")

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nome


class Transactions(models.Model):
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
        )        
    created = models.DateTimeField(auto_now_add=True)
    tipo = models.CharField(max_length=255, blank=False, null=False)
    valor = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        blank=False,
        null=False,
    )
    conta = models.ForeignKey(
        BankAccount, on_delete=models.PROTECT,
    )
    contato = models.ForeignKey(
        Contacts,
        on_delete=models.PROTECT,
        blank=True, null=True, default=None,
        related_name='transactions',
    )
    descricao = models.CharField(max_length=255, blank=False, null=False)
    categoria = models.ForeignKey(
        Categories,
        on_delete=models.DO_NOTHING,
        related_name='transaction',
        blank=True,
        null=True,
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='transactions',
    )
    linked = models.OneToOneField(
        'Transactions',
        on_delete=models.CASCADE,
        blank=True, null=True, default=None,
    )    

    def __str__(self):
        return f'{self.descricao}' 

modules/finance/models.py
from django.db import models
from django.core.exceptions import ValidationError

from modules.erp.models import Company
from modules.users.models import User
from modules.contacts.models import Contacts

import uuid


class BankAccount(models.Model):
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
        )        
    created = models.DateTimeField(auto_now_add=True)
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name='banks',
    )
    nome = models.CharField(max_length=255)
    agencia = models.CharField(max_length=255, blank=True)
    conta = models.CharField(max_length=255, blank=True)
    saldo = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True, default=0,
    )

    def __str__(self):
        return f'{self.nome}'
    

class Categories(models.Model):
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
        )
    parent = models.ForeignKey(
        'self', 
        on_delete=models.CASCADE, 
        related_name='subcategories',
        blank=True, 
        null=True, 
    )
    nome = models.CharField(max_length=150)
    is_active = models.BooleanField(default=True)
    is_group = models.BooleanField(default=False)

    def clean(self):
        if self.parent and not self.parent.is_group:
            raise ValidationError("Parent must have is_group=True")

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nome


class Transactions(models.Model):
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
        )        
    created = models.DateTimeField(auto_now_add=True)
    tipo = models.CharField(max_length=255, blank=False, null=False)
    valor = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        blank=False,
        null=False,
    )
    conta = models.ForeignKey(
        BankAccount, on_delete=models.PROTECT,
    )
    contato = models.ForeignKey(
        Contacts,
        on_delete=models.PROTECT,
        blank=True, null=True, default=None,
        related_name='transactions',
    )
    descricao = models.CharField(max_length=255, blank=False, null=False)
    categoria = models.ForeignKey(
        Categories,
        on_delete=models.DO_NOTHING,
        related_name='transaction',
        blank=True,
        null=True,
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='transactions',
    )
    linked = models.OneToOneField(
        'Transactions',
        on_delete=models.CASCADE,
        blank=True, null=True, default=None,
    )    

    def __str__(self):
        return f'{self.descricao}' 

finance/forms.py
from django.forms import ModelForm, ChoiceField

from .models import Transactions, BankAccount, Categories
from contacts.models import Contacts


class TransactionsForm(ModelForm):
    class Meta:
        model = Transactions
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        company = kwargs.pop('company')
        super(TransactionsForm, self).__init__(*args, **kwargs)

        self.fields['conta'].queryset = BankAccount.objects \
            .filter(company=company) \
            .order_by('-saldo')
        
        self.fields['contato'].queryset = Contacts.objects \
            .filter(company=company) \
            .order_by('nome')  

        category_groups = Categories.objects \
            .filter(is_group=True, is_active=True) \
            .order_by('-nome') \

        subcategories = Categories.objects \
            .filter(is_group=False, is_active=True) \
            .order_by('nome')

        categorias = {}
        for group in category_groups:
            categorias[group.nome] = {'subcategorias': []}

        for sub in subcategories:
            categorias[sub.parent.nome]['subcategorias'].append({'nome': sub.nome, 'id': str(sub.id)})

        self.category = categorias
        
        self.fields['conta'].empty_label = 'escolha conta'
        self.fields['contato'].empty_label = 'escolha contato'
        self.fields['categoria'].empty_label = 'escolha categoria'

        for _, field in self.fields.items():
            field.widget.attrs.update({
                'autofocus': True,
                'class': '''
                    placeholder:text-black dark:placeholder:text-white
                    appearance-none w-full
                    bg-transparent
                    outline-none''',
            })            


class BankAccountForm(ModelForm):
    class Meta:
        model = BankAccount
        fields = '__all__'


class CategoriesForm(ModelForm):
    class Meta:
        model = Categories
        fields = ["nome", "parent"]

modules/finance/forms.py
from django.forms import ModelForm, ChoiceField

from .models import Transactions, BankAccount, Categories
from modules.contacts.models import Contacts


class TransactionsForm(ModelForm):
    class Meta:
        model = Transactions
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        company = kwargs.pop('company')
        super(TransactionsForm, self).__init__(*args, **kwargs)

        self.fields['conta'].queryset = BankAccount.objects \
            .filter(company=company) \
            .order_by('-saldo')
        
        self.fields['contato'].queryset = Contacts.objects \
            .filter(company=company) \
            .order_by('nome')  

        category_groups = Categories.objects \
            .filter(is_group=True, is_active=True) \
            .order_by('-nome') \

        subcategories = Categories.objects \
            .filter(is_group=False, is_active=True) \
            .order_by('nome')

        categorias = {}
        for group in category_groups:
            categorias[group.nome] = {'subcategorias': []}

        for sub in subcategories:
            categorias[sub.parent.nome]['subcategorias'].append({'nome': sub.nome, 'id': str(sub.id)})

        self.category = categorias
        
        self.fields['conta'].empty_label = 'escolha conta'
        self.fields['contato'].empty_label = 'escolha contato'
        self.fields['categoria'].empty_label = 'escolha categoria'

        for _, field in self.fields.items():
            field.widget.attrs.update({
                'autofocus': True,
                'class': '''
                    placeholder:text-black dark:placeholder:text-white
                    appearance-none w-full
                    bg-transparent
                    outline-none''',
            })            


class BankAccountForm(ModelForm):
    class Meta:
        model = BankAccount
        fields = '__all__'


class CategoriesForm(ModelForm):
    class Meta:
        model = Categories
        fields = ["nome", "parent"]

finance/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect

from erp.services import Settings
from .services import Finance

from .models import Transactions, BankAccount


def has_company(user):
    return hasattr(user, 'company') and user.company is not None

@user_passes_test(has_company, login_url='users:login')
def caixa(request):
    context = Settings.context(request)
    context.update(Finance.context(request))

    return render(request, 'finance/main.html', context)

@login_required(login_url='users:login')
def delete_transaction(request, pk):
    transaction = Transactions.objects.get(pk=pk)

    if request.method == 'POST':
        transaction.delete()

    return redirect(request.META.get('HTTP_REFERER', 'finance:caixa')) 

@login_required(login_url='users:login')
def delete_bank(request, pk):
    bank = BankAccount.objects.get(pk=pk)
    transactions = Transactions.objects.filter(conta=bank)

    if request.method == 'POST' and 'delete-bank' in request.POST:
        if not transactions:
            bank.delete()
        else:
            print('banco possui lançamentos, para')

    return redirect('finance:caixa')

modules/finance/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect

from modules.erp.services import Settings
from .services import Finance

from .models import Transactions, BankAccount


def has_company(user):
    return hasattr(user, 'company') and user.company is not None

@user_passes_test(has_company, login_url='users:login')
def caixa(request):
    context = Settings.context(request)
    context.update(Finance.context(request))

    return render(request, 'finance/main.html', context)

@login_required(login_url='users:login')
def delete_transaction(request, pk):
    transaction = Transactions.objects.get(pk=pk)

    if request.method == 'POST':
        transaction.delete()

    return redirect(request.META.get('HTTP_REFERER', 'finance:caixa')) 

@login_required(login_url='users:login')
def delete_bank(request, pk):
    bank = BankAccount.objects.get(pk=pk)
    transactions = Transactions.objects.filter(conta=bank)

    if request.method == 'POST' and 'delete-bank' in request.POST:
        if not transactions:
            bank.delete()
        else:
            print('banco possui lançamentos, para')

    return redirect('finance:caixa')

modules/finance/templates/finance/common/modals/_add_account.html
{% load static %}
{% load finance %}

<div
    id="addAccount"
    class="
        hidden
        fixed
        inset-0 z-50 
        justify-center items-center
        bg-background/20 dark:bg-black/40
        backdrop-blur-md">
  
    <div 
      class=
        "ring-1
        ring-primary/10
        dark:ring-white/15
        bg-white dark:bg-secondary
        shadow-xl
        p-4
        lg:w-4/12 sm:h-3/5
        md:w-7/12
        w-11/12 h-[75%]
        rounded-2xl
        relative"> 

        <form action="{% url "finance:caixa" %}" method="POST" class="">
            {% csrf_token %}
            <div
                class="px-1 mt-4 mb-6 text-4xl text-start text-black/75 dark:text-white/75">
                nova conta
            </div>

            <div
                class="px-1 text-sm text-start text-black/70 dark:text-white/70">
                <p>saldo inicial</p>
            </div>

            <div class="relative justify-center items-center px-1 pt-0 pb-2">
                <label class="flex text-black/40 dark:text-white/40 text-3xl">
                    R$
                    <input
                        class="valor px-1 w-fit text-3xl outline-none bg-transparent text-black/40 dark:text-white/40 placeholder:text-black/40 dark:placeholder:text-white/40"
                        name="saldo"
                        id="saldo"
                        inputmode="decimal"
                        placeholder="0,00">
                    </input>
                </label>
            </div>      

            <div class="flow-root rounded-lg bg-background/50 dark:bg-tertiary ring-1 ring-black/10 py-2 mt-2">
                <dl class="-my-3 divide-y divide-black/5 dark:divide-white/5 text-sm">
              
                  <div class="grid grid-cols-1 gap-1 p-3">
                    <dt class="text-black/70 dark:text-white/70">nome</dt>
                    <input
                        required
                        name="nome"
                        id="nome"
                        value=""
                        placeholder="..."
                        class="text-black/40 dark:text-white/40 placeholder:text-black/40 placeholder:dark:text-white/40 bg-transparent outline-none sm:col-span-2 text-start">
                    </input>
                  </div>
              
                  <div class="grid grid-cols-1 gap-1 p-3">
                    <dt class="text-black/70 dark:text-white/70">agência</dt>
                    <input
                        name="agencia"
                        id="agencia"
                        value=""
                        placeholder="..."
                        class="text-black/40 dark:text-white/40 placeholder:text-black/40 placeholder:dark:text-white/40 bg-transparent outline-none sm:col-span-2 text-start">
                    </input>
                  </div>

                  <div class="grid grid-cols-1 gap-1 p-3">
                    <dt class="text-black/70 dark:text-white/70">conta</dt>
                    <input
                        name="conta"
                        id="conta"
                        value=""
                        placeholder="..."
                        class="text-black/40 dark:text-white/40 placeholder:text-black/40 placeholder:dark:text-white/40 bg-transparent outline-none sm:col-span-2 text-start">
                    </input>
                  </div>                  
                </dl>
            </div>

            <!--bottom-right submit button-->   
            <div class="absolute bottom-4 right-4 text-sm leading-5">
                <button
                    class="
                    group
                    flex 
                    p-1
                    items-center justify-center 
                    aspect-square rounded-md 
                    dark:shadow-thick 
                    ring-1 
                    ring-primary/15 hover:ring-primary/10
                    dark:ring-white/10 dark:hover:ring-white/20
                    duration-300 
                    transition-all
                    bg-white dark:bg-tertiary
                    hover:bg-zinc-100 dark:hover:bg-primary"                    
                    type="submit" 
                    name="add-account">
                    <svg class="size-[18px] stroke-black/55 dark:stroke-white/60" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                    </svg>                                                         
                </button>
            </div>                                    
        </form>

        <!--bottom-left closeAddAccount button-->  
        <div class="absolute bottom-4 left-4 text-sm leading-5">
            <p
                class="
                group
                flex 
                p-1
                items-center justify-center 
                aspect-square rounded-md 
                dark:shadow-thick 
                ring-1 
                ring-primary/15 hover:ring-primary/10
                dark:ring-white/10 dark:hover:ring-white/20
                duration-300 
                transition-all
                bg-white dark:bg-tertiary
                hover:bg-zinc-100 dark:hover:bg-primary">
                <a id="closeAddAccount" href="javascript:history.back()">
                    <svg class="size-[18px] text-black/55 dark:text-white/60" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6 18 17.94 6M18 18 6.06 6"/>
                    </svg>                                                    
                </a>
            </p>
        </div>            
  
    </div>
</div>

<script src="{% static "js/finance/addAccount.js" %}"></script>
<script src="https://unpkg.com/imask"></script>
<script>
    const valorInputs = document.querySelectorAll('.valor');
    valorInputs.forEach(input => {
        IMask(input, {
            mask: Number,
            scale: 2,
            thousandsSeparator: '.',
            radix: ',',
            padFractionalZeros: true,
        });
    });
</script>

modules/finance/templates/finance/common/modals/_edit_account.html
{% load static %}
{% load finance %}
{% load filters %}

<div id="editBankAccount" 
    class="
    overflow-hidden
    col-span-2    
    hidden
    fixed
    inset-0 z-50 
    justify-center items-center
    bg-background/20 dark:bg-black/40 backdrop-blur-md">

    <div class="
        relative
        overflow-auto
        flex
        shadow-xl rounded-2xl ring-1 ring-black/10 dark:ring-white/10 sm:dark:ring-white/20
        h-[75%] w-11/12
        sm:h-3/5 lg:w-4/12 md:w-7/12">

        <div class="overflow-x-auto p-0 flex gap-3 no-scrollbar snap-mandatory snap-x">
            {% for bank in banks %}
            <div
                class="
                snap-always snap-center
                ring-1 
                ring-black/5 dark:ring-white/5
                bg-white
                dark:bg-secondary      
                shadow-md         
                p-4
                relative  
                rounded-2xl
                h-full w-full
                flex-shrink-0">     

                {% if banks|length > 1 %}
                {% if forloop.first %}
                <div class="px-4 w-full top-0">
                    <p class="text-center text-[13px] text-black/40 dark:text-white/40">
                        arraste para o lado
                    </p>
                </div>    
                {% endif %}   
                {% endif %}   
                
                <form action="{% url "finance:caixa" %}" method="POST" class="">
                    {% csrf_token %}
                    <div
                        class="px-1 mt-6 text-4xl leading-none text-start tracking-normal sm:tracking-normal text-black/70 dark:text-white/80">
                        <span>{{ bank.nome | lower }}</span>
                    </div>

                    <div class="relative justify-center items-center px-1 mb-8">
                        <label class="flex text-black/40 dark:text-white/40 text-lg">
                            R$
                            <input
                                class="valor px-1 w-fit text-lg outline-none bg-transparent text-black/40 dark:text-white/40 placeholder:text-black/40 dark:placeholder:text-white/40"
                                name="saldo"
                                id="saldo"
                                value="{{ bank.saldo | format_money }}"
                                inputmode="decimal"
                                placeholder="0,00">
                        </label>
                    </div>   
        
                    <div class="flow-root py-2 mt-2 rounded-lg bg-background/50 dark:bg-tertiary ring-1 ring-black/10">
                        <dl class="-my-3 divide-y divide-black/5 dark:divide-white/5 text-sm">
                      
                          <div class="grid grid-cols-1 gap-1 p-3">
                            <dt class="text-black/70 dark:text-white/70">nome</dt>
                            <input
                                required
                                name="name"
                                id="name"
                                value="{{ bank.nome | lower }}"
                                placeholder="..."
                                class="text-black/40 dark:text-white/40 placeholder:text-black/40 placeholder:dark:text-white/40 bg-transparent outline-none sm:col-span-2 text-start">
                          </div>
                      
                          <div class="grid grid-cols-1 gap-1 p-3">
                            <dt class="text-black/70 dark:text-white/70">agência</dt>
                            <input
                                name="agencia"
                                id="agencia"
                                {% if bank.agencia %}value="{{ bank.agencia }}" {% endif %}
                                placeholder="..."
                                class="text-black/40 dark:text-white/40 placeholder:text-black/40 placeholder:dark:text-white/40 bg-transparent outline-none sm:col-span-2 text-start">
                          </div>
        
                          <div class="grid grid-cols-1 gap-1 p-3">
                            <dt class="text-black/70 dark:text-white/70">conta</dt>
                            <input
                                name="conta"
                                id="conta"
                                {% if bank.conta %}value="{{ bank.conta }}" {% endif %}
                                placeholder="..."
                                class="text-black/40 dark:text-white/40 placeholder:text-black/40 placeholder:dark:text-white/40 bg-transparent outline-none sm:col-span-2 text-start">
                          </div>  

                          <div class="hidden grid-cols-1 gap-1 p-3">
                            <dt class="text-black/70 dark:text-white/70">id</dt>
                            <input
                                name="id"
                                id="id"
                                value="{{ bank.id }}"
                                placeholder="..."
                                class="text-black/40 dark:text-white/40 placeholder:text-black/40 placeholder:dark:text-white/40 bg-transparent outline-none sm:col-span-2 text-start">
                          </div>   

                          <div class="hidden grid-cols-1 gap-1 p-3">
                            <dt class="text-black/70 dark:text-white/70">company</dt>
                            <input
                                name="company"
                                id="company"
                                value="{{ bank.company.cnpj }}"
                                placeholder="..."
                                class="text-black/40 dark:text-white/40 placeholder:text-black/40 placeholder:dark:text-white/40 bg-transparent outline-none sm:col-span-2 text-start">
                          </div>                            
                        </dl>
                    </div>
        
                    <!--bottom-right submit button-->  
                    <div class="absolute bottom-4 right-4 text-sm leading-5">
                        <button
                            class="
                            group
                            flex 
                            p-1
                            items-center justify-center 
                            aspect-square rounded-md 
                            dark:shadow-thick 
                            ring-1 
                            ring-primary/15 hover:ring-primary/10
                            dark:ring-white/10 dark:hover:ring-white/20
                            duration-300 
                            transition-all
                            bg-white dark:bg-tertiary
                            hover:bg-zinc-100 dark:hover:bg-primary"
                            type="submit" 
                            name="edit-account">
                            <svg class="size-[18px] stroke-black/55 dark:stroke-white/60" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                            </svg>                        
                        </button>
                    </div>            
                </form>   
                
                <!--bottom-left delete button-->  
                <form action="{% url "finance:delete_bank" bank.id %}" method="POST">
                {% csrf_token %}
                <div class="absolute bottom-4 left-4 text-sm leading-5">
                        <button
                            class="
                            group
                            flex 
                            p-1
                            items-center justify-center 
                            aspect-square rounded-md 
                            dark:shadow-thick 
                            ring-1 
                            ring-red-200 hover:ring-red-300
                            dark:ring-red-700/50 dark:hover:ring-red-600/60
                            duration-300 
                            transition-all
                            bg-white dark:bg-secondary
                            hover:bg-red-50 dark:hover:bg-primary"
                            type="submit"
                            name="delete-bank">
                            <svg class="size-[18px] stroke-red-400 dark:stroke-red-400/70" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                            </svg>                                                                                                      
                        </button>
                    </div>   
                </form>                 

            </div>
            {% endfor %}
            <input class="bg-transparent">              
        </div>        
        
        <!--empty closeHistory button-->  
        <div class="absolute top-4 left-5 sm:left-4 text-sm leading-5">
            <button id="closeBankAccount">             
            </button>
        </div>            
    </div>
</div>

<script src="{% static "js/finance/editAccount.js" %}"></script>